describe("moveAbout", () => {
  it("About 페이지로 접근합니다.", () => {
    cy.visit("/")
    cy.get("a.nav-link")
      .contains("About")
      .click()
    cy.wait(1000)
    cy.url()
      .should("include", "/about")
    cy.get(".name")
      .contains("HVRAIN")
  })
  it("영화 상세 페이지로 접근합니다.", () => {
    cy.get("a.nav-link")
      .contains("Movie")
      .click()
    cy.wait(1000)
    cy.url()
      .should("include", "/movie")
    cy.get(".title")
      .contains("Frozen II")
  })
  it("About 페이지로 접근합니다.", () => {
    cy.get("a.nav-link")
      .contains("About")
      .click()
    cy.wait(1000)
    cy.get("a.nav-link.active")
      .contains("About")
  })
})